### ISSUE TITLE
Can not place links on images in markdown.

### ISSUE THREAD

**Issue by nicholasgkdto** [AusDTO/gov-au-beta#461] opened 2016-09-01 00:34 UTC
When I try to add a link to an image with markdown, it renders the html code and not the image.

Markdown i use:
`[![My alt text](https://avatars2.githubusercontent.com/u/19787722?v=3&s=88)](http://www.google.com)`

Expected results
[![My alt text](https://avatars2.githubusercontent.com/u/19787722?v=3&s=88)](http://www.google.com)

Results I get
[`<img src="https://avatars2.githubusercontent.com/u/19787722?v=3&s=88" alt="My alt text">`](http://www.google.com)

an example can be see here 
platform/department-of-communications-and-the-arts/news/2016-07-28-panel-presentation-the-art-of-change

I had to change it to just a link, but if you look at some of the page in the history it will be there

**Comment by ltankey** [comment] 2016-09-01 02:08
Confirmed - looks like a bug with our rendered output. Potentially related to our usage of RedCarpet - doesn't seem to happen in a kramdown renderer. SITES-672

**Comment by bjgordon** [comment] 2016-09-07 03:01
Fixed in v1.3.0

**Closed by bjgordon** 2016-09-07 03:01 UTC
Labels: bug
